name: ci
on:
  push:

jobs:
  build-enclave-rpc:
    runs-on: ubuntu-22.04
    permissions:
      id-token: write
      contents: read
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Install cosign
      uses: sigstore/cosign-installer@v3.6.0
    - name: Install Rust
      uses: actions-rust-lang/setup-rust-toolchain@v1
      with:
        toolchain: nightly
        target: x86_64-unknown-linux-musl
    - name: Build
      run: |
        set -e
        cd enclave-rpc
        cargo build --release --locked
        mkdir build
        cp ./target/x86_64-unknown-linux-musl/release/enclave-rpc ./build/
        cd build
        sha256sum enclave-rpc
    - name: Sign
      run: |
        set -e
        cd enclave-rpc/build
        cosign sign-blob -y --bundle ./enclave-rpc.bundle.json ./enclave-rpc
        ls -lash
        cat enclave-rpc.bundle.json
    - name: Push binaries
      uses: actions/upload-artifact@v4
      with:
        name: enclave-rpc
        path: ./enclave-rpc/build
  build-securelink:
    runs-on: ubuntu-22.04
    permissions:
      id-token: write
      contents: read
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Install cosign
      uses: sigstore/cosign-installer@v3.6.0
    - name: Install Rust
      uses: actions-rust-lang/setup-rust-toolchain@v1
      with:
        toolchain: nightly
    - name: Install Node
      uses: actions/setup-node@v4
      with:
        node-version: 20
    - name: Build
      run: |
        set -e
        cd securelink
        npm ci
        npm run build-wasm
        npm run check
        npm run bundle
        cd build
        sha256sum vwcrypto.wasm connect.mjs | tee SHA256SUMS
    - name: Sign
      run: |
        set -e
        cd securelink/build
        cosign sign-blob -y --bundle ./SHA256SUMS.bundle.json ./SHA256SUMS
        ls -lash
        cat SHA256SUMS.bundle.json
    - name: Push binaries
      uses: actions/upload-artifact@v4
      with:
        name: securelink
        path: ./securelink/build
  publish-securelink:
    runs-on: ubuntu-22.04
    environment: cf-pages
    permissions:
      id-token: write
      contents: write
      deployments: write
    if: startsWith(github.ref, 'refs/tags/')
    needs:
    - build-securelink
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Prepare
      run: |
        set -e
        mkdir web
    - name: Download artifacts
      uses: actions/download-artifact@v4
      with:
        name: securelink
        path: ./web/run
    - name: Publish to Cloudflare Pages
      uses: cloudflare/pages-action@v1
      with:
        apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
        accountId: 33ec30ecf17c12fd7704767077b686a3
        projectName: ssci-dev
        directory: web
        gitHubToken: ${{ secrets.GITHUB_TOKEN }}
        branch: main
  release:
    runs-on: ubuntu-22.04
    permissions:
      id-token: write
      contents: write
    if: startsWith(github.ref, 'refs/tags/')
    needs:
    - build-enclave-rpc
    - build-securelink
    env:
      PACKAGE_NAME_ENCLAVE_RPC: enclave-rpc-${{ github.ref_name }}.tar.gz
      PACKAGE_NAME_SECURELINK: securelink-${{ github.ref_name }}.tar.gz
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Download artifacts (enclave-rpc)
      uses: actions/download-artifact@v4
      with:
        name: enclave-rpc
        path: ./enclave-rpc-build
    - name: Download artifacts (securelink)
      uses: actions/download-artifact@v4
      with:
        name: securelink
        path: ./securelink-build
    - name: Package
      run: |
        set -e
        cd enclave-rpc-build
        chmod +x enclave-rpc
        tar c . | gzip > ../$PACKAGE_NAME_ENCLAVE_RPC
        cd ../securelink-build
        tar c . | gzip > ../$PACKAGE_NAME_SECURELINK
    - name: Publish release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          ${{ env.PACKAGE_NAME_ENCLAVE_RPC }}
          ${{ env.PACKAGE_NAME_SECURELINK }}
        prerelease: true
